spring.application.name=blsd-api-bend

spring.datasource.url=jdbc:h2:mem:exemplorelacionamento

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true

spring.web.error.include-binding-errors=always
spring.web.error.include-message=always